# Generated by Django 3.2.4 on 2021-07-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
