# Generated by Django 3.2.4 on 2021-07-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='average rating'),
        ),
    ]
