# Generated by Django 3.2.4 on 2021-08-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210802_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='default',
        ),
    ]
