# Generated by Django 3.2.4 on 2021-08-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productimage_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='extra_images',
        ),
    ]
